debug: true

spring:
  kafka:
    bootstrap-servers: 192.168.0.64:9092
    template:
      default-topic: players
    producer:
      properties:
        spring.json.type.mapping: player:com.example.spring.batch.kafka.domain.Player
        spring.json.trusted.packages: "*"
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
